### PR TITLE
Add requirement about python3-devel

### PR DESCRIPTION
**Pull request by razzeee**
This was failing for me and I needed some time to find the problem, so I think it makes sense to mention it.

### CODE REVIEW

**Comment by refi64** [comment]
What was the exact problem you hit? All the generator's dependencies should be wheels, so I'm surprised you needed python3-devel...

**Comment by razzeee** [comment]
If I remember right, it couldn't build a wheel as it was missing a header

**Comment by razzeee** [comment]
I ended up on this SO https://stackoverflow.com/questions/34668675/cython-fatal-error-python-h-no-such-file-or-directory

**Comment by refi64** [comment]
Hmm so I just tried this in a Fedora docker image, with no Python development files installed or even a C compiler, and it still installed...any chance you could try reinstalling it *without* the python3-devel package, and share the original error here?

**Comment by razzeee** [comment]
Hrm, tried this in a fedora 36 vm I had laying around and it just worked. Without `python3-devel` installed, so I too am confused about this.

Should we close it?

**Comment by refi64** [comment]
...out of curiosity, were you on the Fedora 37 beta? It would actually make sense there, because they shipped Python 3.11's rc versions, probably before wheels were readily available for some dependencies.

**Comment by razzeee** [comment]
Yes, that's was/is the case.

**Pull request closed without merging**
