### PR TITLE
go-get: Add more known module URL replacements

### PR DESCRIPTION
**Pull request by joaquimrocha**
This patch adds some more replacements for known go modules' URLs.

### CODE REVIEW

**Comment by muelli** [comment]
LGTM.
I wonder: Can the list be found in the Go sources somewhere? maybe even re-used so that we don't have to maintain this list ourselves?

**Comment by joaquimrocha** [comment]
I will try to find a way to get these automatically. Maybe checking the URL redirects is good enough.

**Comment by joaquimrocha** [comment]
@muelli , I have updated the patch. It now follows a similar logic to the `go get` command.

**Comment by joaquimrocha** [comment]
I forgot something important in the script. I'll fix it in a couple it hours. Don't merge.

**Comment by joaquimrocha** [comment]
Should be fine now.

**Comment by muelli** [comment]
works well for me (that is, syncthing).

It's a bit noisy for my taste, but that can be addressed later, if at all.

Thanks a million!

**Pull request merged**
