### PR TITLE
pip: adapt generator to be imported by other files

### PR DESCRIPTION
**Pull request by jacobszpz**
Just throwing an idea out here, but I have a use case where functions such as 'get_pypi_url' are useful to me and I am already using this script anyway. However, it is impossible to import from other files because there is no if __name__ == '__main__' clause in the script, as well as the script having no .py extension and having dashes in its name. I don't know if this aligns with your goals, but maybe you'd like to consider it.

### CODE REVIEW

**Comment by jacobszpz** [comment]
For compatibility's sake, you could keep the original script as a wrapper and import the new version using exec

**Comment by jacobszpz** [comment]
I also have added an option to the CLI to only download the main packages listed and not fetch all their dependencies

**Comment by TingPing** [comment]
You will need to update all documentation.

I think its a slight downgrade for normal users but... its pretty minor.

**Comment by jacobszpz** [comment]
Nah, I agree. I ended up not using this particular method anyway.

**Pull request closed without merging**
