### PR TITLE
Add support for git+ssh scheme

### PR DESCRIPTION
**Pull request by proletarius101**
So naively adding this to the support list works.

### CODE REVIEW

**Comment by muelli** [comment]
what problem does that fix for you?

**Comment by proletarius101** [comment]
> what problem does that fix for you?

e.g. In https://github.com/bitwarden/desktop/blob/master/package.json#L309 they use `git+ssh`, which we would like to build from source: https://github.com/flathub/com.bitwarden.desktop/pull/52. This type of dependencies will abort the flatpak-builder-tools

**Comment by muelli** [comment]
okay, cool! :) I haven't written the generator and I prefer somebody else taking the lead here for merging,  but if I merge this, I just want to make sure it fixes an actual problem rather than something that may be relevant in the future.

And so I wonder: does that really fix the problem? From what I can see the build fails in the download phase.

**Comment by hfiguiere** [comment]
I don't think it should replace to `ssh:` as this require authtentication.

**Comment by gasinvein** [comment]
`git+ssh` should work fine, flatpak-builder is able to handle it as-is. Can you provide at some evidence of what exactly does this fix?

**Comment by muelli** [comment]
let me close for now. Please reopen if this becomes necessary.

**Pull request closed without merging**
