### PR TITLE
Added support for whl extension in package url

### PR DESCRIPTION
**Pull request by TheJackiMonster**
I couldn't generate a dependency file with PyQt5 because the newest version only used .whl files. So the script always failed with an exception.

However adding the extension to the list which will be used for validation worked for me.

### CODE REVIEW

**Comment by nanonyme** [comment]
This absolutely cannot be default behaviour. Some wheels are same (any wheel), they only have generated static metadata, otherwise they are equivalent to source packages. But other wheels have compiled code and they cannot be pulled in without user of tool consenting somehow.

**Comment by nanonyme** [comment]
For compiled wheel even if they are acceptable, those have to be handled manually since you need different sources per architecture.

**Comment by muelli** [comment]
so.. Do we close this as this cannot work reliably? Or do we give it the benefit of doubt, because it works sometimes?

**Comment by TingPing** [comment]
As-is I don't think this should be merged. I think there is a middle ground of trying to use `any.whl`'s and/or making it explicitly opt-in (`--allow-whl-for=foo,bar`) or something.

**Comment by TingPing** [comment]
Actually `any.whl` was supported in https://github.com/flatpak/flatpak-builder-tools/commit/fa73b5df4a46458085e93a929c4e507b3ae45a91

**Comment by nanonyme** [comment]
Yeah, I the problem is things like Qt5 which indeed have wheels but they are per-arch and have ABI requirements. It's not a straightforward task to say what kind of manifest should be generated.

**Comment by nanonyme** [comment]
Other unpleasant packages contains cryptography which assumes you have a Rust compiler if you want source install. But at least it can be done.

**Pull request closed without merging**
