### PR TITLE
generate sources from yarn.lock

### PR DESCRIPTION
**Pull request by adityashah1212**

### CODE REVIEW

**Comment by nedrichards** [comment]
I am very excited to see this! Will take a closer look later.

**Comment by nedrichards** [comment]
This by and large looks 'fine' from a read. I'm going to try and use it to package a simple project and if it works, happy to merge since it's an entirely new system.

I'd love to see a README.md added to give people a bit more documentation but that can be added later if you don't have time now.

**Comment by adityashah1212** [comment]
there is still one thing missing in this. It seems that there are instances where git urls are given as git+https or git+http or git+ssh. I have seen it, but I am waiting on this pull request to merge. I want to keep it separate.

**Comment by nedrichards** [comment]
Makes sense. I wasn't able to test this fully as the system with a new enough flatpak and flatpak-builder didn't have enough RAM to build nodejs - but I was able to test both parts enough to know that it does what it's supposed to!

**Pull request merged**
