### PR TITLE
Add --yaml flag to flatpak-pip-generator

### PR DESCRIPTION
**Pull request by JakobDev**
The new YAML flags allows writing the output as YAML instead of JSON.

### CODE REVIEW

**Comment by TingPing** [comment]
I fail to see the value of this.

- YAML files can include JSON files
- These are automatically generated files that people will rarely read and shouldn't edit

**Comment by JakobDev** [comment]
There are people who read it and I see some people who convert the generated JSON to YAML. This are only a few lines for people who prefer to have everything as YAML.

**Comment by hfiguiere** [comment]
> There are people who read it 

sure, and JSON can be read too.

> and I see some people who convert the generated JSON to YAML. 

That doesn't justify it.

**Comment by JakobDev** [comment]
> sure, and JSON can be read too.

It' harder to read than YAML

> That doesn't justify it.

If it actually used out there, there are a reason to implement this.

**Comment by TingPing** [comment]
It is a really tiny patch so I won't argue against it too much.

**Pull request merged**
