### PR TITLE
cargo: Embed resolved manifest in generated sources

### LINKED ISSUE #348: cargo generator doesn't include ``.workspace`` versions
### flatpak-builder version

1.2.3

### Linux distribution and version

NixOS 23.05

### Affected flatpak-builder tool

cargo/flatpak-cargo-generator.py

### flatpak-builder tool cli args

_No response_

### Source repository URL

https://github.com/tauri-apps/plugins-workspace/blob/dev/plugins/window-state/Cargo.toml

### Flatpak-builder manifest URL

https://github.com/flathub/dev.slimevr.SlimeVR

### Description

When trying to build a git dependency that is inside a workspace, cargo can take into account the root of the workspace for versions. The generator doesnt take that into account.

### PR DESCRIPTION
**Pull request by gasinvein**
Cargo with `inherit-workspace` feature requires workspace packages Cargo.toml's to be resolved when using vendored sources, because the workspace manifest won't be available when building them.
Fixes #348 
See also https://github.com/rust-lang/cargo/pull/11414

### CODE REVIEW

**Comment by gasinvein** [comment]
@tim77 @sebastian-de @muelli Can you please test this patched cargo generator with the apps you maintain (Veloren, Lapce and Delta Chat respectively (these three are known to be the complex rust app on Flathub and heavily use packages from git))?

**Comment by sebastian-de** [comment]
Hi @gasinvein, thanks for reaching out.
I did a quick test with https://raw.githubusercontent.com/lapce/lapce/master/Cargo.lock which yields:
```
[...]
INFO:root:Loading packages from https://github.com/lapce/wasi-experimental-http
DEBUG:root:Loading dependency wasi-experimental-http from crates/wasi-experimental-http
DEBUG:root:Loading dependency wasi-experimental-http-wasmtime from crates/wasi-experimental-http-wasmtime
DEBUG:root:Loading workspace member ./crates/wasi-experimental-http/Cargo.toml in /home/sepp/.cache/flatpak-cargo/https_github.com_lapce_wasi-experimental-http
DEBUG:root:Loading workspace member ./crates/wasi-experimental-http-wasmtime/Cargo.toml in /home/sepp/.cache/flatpak-cargo/https_github.com_lapce_wasi-experimental-http
DEBUG:root:Loading workspace member ./tests/rust/Cargo.toml in /home/sepp/.cache/flatpak-cargo/https_github.com_lapce_wasi-experimental-http
DEBUG:root:Packages in https://github.com/lapce/wasi-experimental-http:
{
    "wasi-experimental-http": "crates/wasi-experimental-http",
    "wasi-experimental-http-wasmtime": "crates/wasi-experimental-http-wasmtime",
    "wasi-experimental-http-wasmtime-sample": ".",
    "simple-wasi-http-tests": "tests/rust"
}
INFO:root:Adding package wasi-experimental-http-wasmtime from https://github.com/lapce/wasi-experimental-http
Traceback (most recent call last):
  File "/home/sepp/src/flatpack-cargo-generator-test/./flatpak-cargo-generator.py", line 446, in <module>
    main()
  File "/home/sepp/src/flatpack-cargo-generator-test/./flatpak-cargo-generator.py", line 439, in main
    generated_sources = asyncio.run(generate_sources(load_toml(args.cargo_lock),
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/sepp/src/flatpack-cargo-generator-test/./flatpak-cargo-generator.py", line 393, in generate_sources
    for pkg in await asyncio.gather(*pkg_coros):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sepp/src/flatpack-cargo-generator-test/./flatpak-cargo-generator.py", line 343, in get_package_sources
    return await get_git_package_sources(package, git_repos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sepp/src/flatpack-cargo-generator-test/./flatpak-cargo-generator.py", line 313, in get_git_package_sources
    'contents': toml.dumps(git_pkg.normalized),
                           ^^^^^^^^^^^^^^^^^^
  File "/home/sepp/src/flatpack-cargo-generator-test/./flatpak-cargo-generator.py", line 131, in normalized
    for key, value in section.items():
                      ^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
```
This is probably because https://github.com/lapce/wasi-experimental-http uses a subdirectory called `crates`, but I didn't have a look at your code, yet.

**Comment by gasinvein** [comment]
@sebastian-de Thanks for the feedback. I've updated the PR (force-pushed), can you try again with these changes, please?

**Comment by sebastian-de** [comment]
@gasinvein with your latest change the script runs fine and generates valid sources. I also did a test build of the Lapce Flatpak with the new script - works!

**Comment by gasinvein** [comment]
Ok, thanks, then I believe it should be good to go.

**Pull request merged**
