### PR TITLE
Keep using 'any' wheels

### LINKED ISSUE #226: Flatpak-pip-generator fails to build python-dateutils
Trying to build `python-dateutils` gives the error below.
```
Emptying app dir 'build-dir'
Downloading sources
Starting build of com.gitlab.greenbeast.elephantremember
Cache miss, checking out last cache hit
========================================================================
Building module python3-python-dateutil in /home/hank/Development/elephant_remember/.flatpak-builder/build/python3-python-dateutil-3
========================================================================
Running: pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} "python-dateutil==2.8.1" --no-build-isolation
Using pip 21.0.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
Non-user install due to --prefix or --target option
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /tmp/pip-ephem-wheel-cache-83t0cdmr
Created temporary directory: /tmp/pip-req-tracker-pslyogwh
Initialized build tracking at /tmp/pip-req-tracker-pslyogwh
Created build tracker: /tmp/pip-req-tracker-pslyogwh
Entered build tracker: /tmp/pip-req-tracker-pslyogwh
Created temporary directory: /tmp/pip-install-wf4vu06l
Looking in links: file:///run/build/python3-python-dateutil
0 location(s) to search for versions of python-dateutil:
Skipping link: not a file: file:///run/build/python3-python-dateutil (from -f)
Found link file:///run/build/python3-python-dateutil/python-dateutil-2.8.1.tar.gz, version: 2.8.1
Local files found: /run/build/python3-python-dateutil/python-dateutil-2.8.1.tar.gz
Given no hashes to check 1 links for project 'python-dateutil': discarding no candidates
Processing ./python-dateutil-2.8.1.tar.gz
  Added python-dateutil==2.8.1 from file:///run/build/python3-python-dateutil/python-dateutil-2.8.1.tar.gz to build tracker '/tmp/pip-req-tracker-pslyogwh'
    Created temporary directory: /tmp/pip-modern-metadata-2zirbdxw
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  Removed python-dateutil==2.8.1 from file:///run/build/python3-python-dateutil/python-dateutil-2.8.1.tar.gz from build tracker '/tmp/pip-req-tracker-pslyogwh'
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'python-dateutil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 83, in from_requirement
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('python-dateutil==2.8.1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 320, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('python-dateutil==2.8.1'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for python-dateutil==2.8.1
Removed build tracker: '/tmp/pip-req-tracker-pslyogwh'

```

My requirements json looks like:

```
{
    "name": "python3-requirements",
    "buildsystem": "simple",
    "build-commands": [],
    "modules": [
        {
            "name": "python3-python-dateutil",
            "buildsystem": "simple",
            "build-commands": [
                "pip3 install --verbose --exists-action=i --no-build-isolation --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} \"python-dateutil==2.8.1\" --no-build-isolation"
            ],
            "sources": [
                {
                    "type": "file",
                    "url": "https://files.pythonhosted.org/packages/be/ed/5bbc91f03fa4c839c4c7360375da77f9659af5f7086b7a7bdda65771c8e0/python-dateutil-2.8.1.tar.gz",
                    "sha256": "73ebfe9dbf22e832286dafa60473e4cd239f8592f699aa5adaf10050e6e1823c"
                }
            ]
        },
        {
            "name": "python3-icalendar",
            "buildsystem": "simple",
            "build-commands": [
                "pip3 install --verbose --exists-action=i --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} \"icalendar==4.0.7\" --no-build-isolation"
            ],
            "sources": [
                {
                    "type": "file",
                    "url": "https://files.pythonhosted.org/packages/b0/61/eddc6eb2c682ea6fd97a7e1018a6294be80dba08fa28e7a3570148b4612d/pytz-2021.1.tar.gz",
                    "sha256": "83a4a90894bf38e243cf052c8b58f381bfe9a7a483f6a9cab140bc7f702ac4da"
                },
                {
                    "type": "file",
                    "url": "https://files.pythonhosted.org/packages/58/b8/9aa7963f442b2a8bfdfc40eab8bc399c5eaac5711b8919c52122e4903544/icalendar-4.0.7.tar.gz",
                    "sha256": "0fc18d87f66e0b5da84fa731389496cfe18e4c21304e8f6713556b2e8724a7a4"
                },
                {
                    "type": "file",
                    "url": "https://files.pythonhosted.org/packages/be/ed/5bbc91f03fa4c839c4c7360375da77f9659af5f7086b7a7bdda65771c8e0/python-dateutil-2.8.1.tar.gz",
                    "sha256": "73ebfe9dbf22e832286dafa60473e4cd239f8592f699aa5adaf10050e6e1823c"
                }
            ]
        }
    ]
}

```

### PR DESCRIPTION
**Pull request by hfiguiere**
- this should fix some problems with source building when it's not necessary
- this partially revert f732068a39b2cbc662dbd271003a7ef87f9d498f

@Lctrs you did that patch originall, @TingPing you did merge it. 

Closes #226

### CODE REVIEW

**Comment by hfiguiere** [comment]
We were discussing this in the flatpak channel.

**Comment by nanonyme** [comment]
So essentially the context here is that building  package *metadata* is quite complex and this tool routinely fails to generate right deps for it. Any wheels have generated static metadata (human-readable files) so they do not need the original build system and its dependencies but they do not contain any compiled binaries so they do not in reality harm auditing.

**Comment by hfiguiere** [comment]
This also closes #219

**Comment by lpyparmentier** [comment]
Does not work for #239

**Comment by hfiguiere** [comment]
> Does not work for #239, seems related ? with wheel

it's not supposed to. 

PySide is architecture dependent. This is only for architecture independent ('any'). Also PySide doesn't build the standard way either.

**Comment by lpyparmentier** [comment]
@hfiguiere how could I solve this ? could you give me a hint ?

**Pull request merged**
