### PR TITLE
cargo: Properly support git repos with workspaces

### PR DESCRIPTION
**Pull request by gasinvein**
Kind of follow-up for #107 

In order to properly support git repos with workspace instead of single package, we need to parse `Cargo.toml`'s in there to determine what packages they contain.

Doing so, we don't need cached git repos (`cargo/git/db`) at all, so all related stuff can be removed, including siphash module.

This is tested on [Veloren](https://gitlab.com/veloren/veloren).

Possible improvements:
- [ ] Find a faster way to retrieve `Cargo.toml`'s from remote git repos than just cloning whole repo
- [ ] In generated-sources, avoid cloning whole repo for each package contained in it

### CODE REVIEW

**Comment by gasinvein** [comment]
@barthalion @muelli Is this good enough to merge? Currently, it's rather slow on projects with many dependencies from git, but should be reliable enough. We could speed up git processing later on (see "Possible improvements").

**Comment by muelli** [comment]
I've tried this branch for my usecase (deltachat) and it works: https://github.com/flathub/chat.delta.desktop/pull/34.
Thanks for cleaning it up!

**Comment by gasinvein** [comment]
@muelli Huh? Isn't Delta Chat an electron app?

**Comment by muelli** [comment]
yes. but it uses a Rust library.

**Pull request merged**
