### PR TITLE
cargo: Load in-tree dependencies from git packages

### LINKED ISSUE #181: cargo: KeyError 'blurmac'
Cargo.lock is from https://github.com/servo/servo/ project.
```
python3 ./flatpak-cargo-generator.py Cargo.lock -o cargo-sources.json             [15:55:49]

WARNING:root:background_hang_monitor has no source
WARNING:root:bluetooth has no source
WARNING:root:bluetooth_traits has no source
INFO:root:Loading packages from git https://github.com/servo/devices
Traceback (most recent call last):
  File "/home/projects/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 222, in <module>
    main()
  File "/home/projects/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 217, in main
    generated_sources = generate_sources(load_toml(args.cargo_lock))
  File "/home/projects/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 149, in generate_sources
    git_sources, cargo_vendored_entry = get_git_sources(package)
  File "/home/projects/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 113, in get_git_sources
    pkg_subpath = git_cargo_packages[name]
KeyError: 'blurmac'
```

### LINKED ISSUE #212: [cargo] Issue with Git versions of GTK-rs
Cargo.toml dependencies:
```toml
[dependencies]
actix-rt = "1.1.1"
bincode = "1.3.2"
cairo-rs = { git = "https://github.com/gtk-rs/gtk-rs-core.git", features = ["png"] }
chrono = { version = "0.4.19", features = ["unstable-locales"] }
cid = "0.6.1"
directories-next = "2.0.0"
futures = "0.3.13"
gdk = { git = "https://github.com/gtk-rs/gtk3-rs.git" }
gdk-pixbuf = { git = "https://github.com/gtk-rs/gtk-rs-core.git" }
gio = { git = "https://github.com/gtk-rs/gtk-rs-core.git" }
glib = { git = "https://github.com/gtk-rs/gtk-rs-core.git" }
gtk = { git = "https://github.com/gtk-rs/gtk3-rs.git", features = ["v3_24_9"], default-features = false }
ipfs = { git = "https://github.com/Christian7573/rust-ipfs.git", branch = "7573" }
ipfs-api = { version = "0.11.0", features = ["actix"], default-features = false }
lazy_static = "1.4.0"
notify-rust = { version = "4.3.0", features = ["images", "z"], default-features = false }
pango = { git = "https://github.com/gtk-rs/gtk-rs-core.git" }
url = "2.2.1"
urlencoding = "1.1.1"
reqwest = { version = "0.11.1", features = ["blocking"] }
tokio = { version = "0.2", features = ["full"] }
webkit2gtk = { git = "https://github.com/EmmyGH/webkit2gtk-rs.git", features = ["v2_30"] }
```

Error:
```python3
Traceback (most recent call last):
  File "/home/emil/Documents/Projects/oku/./flatpak-cargo-generator.py", line 274, in <module>
    main()
  File "/home/emil/Documents/Projects/oku/./flatpak-cargo-generator.py", line 268, in main
    generated_sources = asyncio.run(generate_sources(load_toml(args.cargo_lock),
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/emil/Documents/Projects/oku/./flatpak-cargo-generator.py", line 224, in generate_sources
    for pkg in await asyncio.gather(*pkg_coros):
  File "/home/emil/Documents/Projects/oku/./flatpak-cargo-generator.py", line 191, in get_package_sources
    return await get_git_sources(package, tarball=git_tarballs)
  File "/home/emil/Documents/Projects/oku/./flatpak-cargo-generator.py", line 156, in get_git_sources
    pkg_subpath = git_cargo_packages[name]
KeyError: 'javascriptcore-rs-sys'
```

[`javascriptcore-rs`](https://github.com/gtk-rs/javascriptcore-rs) is a dependency of `webkit2gtk-rs`.

### PR DESCRIPTION
**Pull request by gasinvein**
Look into dependencies in cargo git packages and load all in-tree dependencies (the ones that have `path` property).
Fixes #181
Fixes #212
Closes #200

### CODE REVIEW

**Comment by gasinvein** [comment]
@okias @EmmyGH Can you please test if this works for your cases?

**Comment by okias** [comment]
```
WARNING:root:background_hang_monitor has no source
WARNING:root:bluetooth has no source
WARNING:root:bluetooth_traits has no source
INFO:root:started sha256(https://codeload.github.com/servo/devices/tar.gz/cb28c4725ffbfece99dab842d17d3e8c50774778)
WARNING:root:canvas has no source
WARNING:root:canvas_traits has no source
WARNING:root:compositing has no source
WARNING:root:constellation has no source
WARNING:root:deny_public_fields has no source
WARNING:root:deny_public_fields_tests has no source
WARNING:root:derive_common has no source
INFO:root:started sha256(https://codeload.github.com/servo/devices/tar.gz/cb28c4725ffbfece99dab842d17d3e8c50774778)
WARNING:root:devtools has no source
WARNING:root:devtools_traits has no source
WARNING:root:dom_struct has no source
WARNING:root:domobject_derive has no source
WARNING:root:embedder_traits has no source
WARNING:root:fallible has no source
INFO:root:started sha256(https://codeload.github.com/servo/fontsan/tar.gz/29e879c870348c4b3fd51086e42dbb6365171479)
WARNING:root:gfx has no source
WARNING:root:gfx_traits has no source
WARNING:root:hashglobe has no source
WARNING:root:jstraceable_derive has no source
WARNING:root:layout_2013 has no source
WARNING:root:layout_2020 has no source
WARNING:root:layout_thread_2013 has no source
WARNING:root:layout_thread_2020 has no source
WARNING:root:layout_traits has no source
WARNING:root:libmlservo has no source
WARNING:root:libservo has no source
WARNING:root:malloc_size_of has no source
WARNING:root:malloc_size_of_tests has no source
WARNING:root:media has no source
WARNING:root:metrics has no source
WARNING:root:metrics_tests has no source
INFO:root:started sha256(https://codeload.github.com/servo/mio/tar.gz/f640fd662db03026ca2a1b21ac1e161ec6f8150b)
INFO:root:started sha256(https://codeload.github.com/servo/rust-mozjs/tar.gz/a8b688ad32a852172536443d77baa844f59a23fa)
INFO:root:started sha256(https://codeload.github.com/servo/mozjs/tar.gz/de147f0cf52da9c84fa95edf09c5f9f84695088c)
WARNING:root:msg has no source
INFO:root:started sha256(https://codeload.github.com/gfx-rs/naga/tar.gz/b278e10ea7c144b2387585c4e81c1d86db8e2def)
WARNING:root:net has no source
WARNING:root:net_traits has no source
INFO:root:started sha256(https://codeload.github.com/servo/openxrs/tar.gz/87c0186c88f6e2bc22dbbe0bf5c02afc60fc37ef)
INFO:root:started sha256(https://codeload.github.com/servo/openxrs/tar.gz/87c0186c88f6e2bc22dbbe0bf5c02afc60fc37ef)
INFO:root:started sha256(https://codeload.github.com/jdm/webrender/tar.gz/920168aff79a7cf52980b0c90965a591f2f4204a)
INFO:root:started sha256(https://codeload.github.com/jdm/webrender/tar.gz/920168aff79a7cf52980b0c90965a591f2f4204a)
WARNING:root:pixels has no source
WARNING:root:profile has no source
WARNING:root:profile_tests has no source
WARNING:root:profile_traits has no source
WARNING:root:range has no source
INFO:root:started sha256(https://codeload.github.com/jdm/raqote/tar.gz/ff5d2d1aa7813dbcacb0d028cf7d17c82a35d9d4)
WARNING:root:script has no source
WARNING:root:script_layout_interface has no source
WARNING:root:script_plugins has no source
WARNING:root:script_plugins_tests has no source
WARNING:root:script_tests has no source
WARNING:root:script_traits has no source
WARNING:root:selectors has no source
WARNING:root:servo has no source
WARNING:root:servo-gst-plugin has no source
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
WARNING:root:servo_allocator has no source
WARNING:root:servo_arc has no source
WARNING:root:servo_atoms has no source
WARNING:root:servo_config has no source
WARNING:root:servo_config_plugins has no source
WARNING:root:servo_geometry has no source
INFO:root:started sha256(https://codeload.github.com/servo/media/tar.gz/b23e72285ecbe352737eafa4100e65763cc9ccfc)
WARNING:root:servo_rand has no source
WARNING:root:servo_remutex has no source
WARNING:root:servo_url has no source
INFO:root:started sha256(https://codeload.github.com/pcwalton/signpost/tar.gz/7ed712507f343c38646b9d1fefd049166f9c9a18)
WARNING:root:simpleservo has no source
WARNING:root:simpleservo_capi has no source
WARNING:root:simpleservo_jniapi has no source
WARNING:root:size_of_test has no source
WARNING:root:std_test_override has no source
WARNING:root:style has no source
WARNING:root:style_derive has no source
WARNING:root:style_tests has no source
WARNING:root:style_traits has no source
WARNING:root:task_info has no source
WARNING:root:to_shmem has no source
WARNING:root:to_shmem_derive has no source
WARNING:root:webdriver_server has no source
WARNING:root:webgpu has no source
INFO:root:started sha256(https://codeload.github.com/jdm/webrender/tar.gz/920168aff79a7cf52980b0c90965a591f2f4204a)
INFO:root:started sha256(https://codeload.github.com/jdm/webrender/tar.gz/920168aff79a7cf52980b0c90965a591f2f4204a)
INFO:root:started sha256(https://codeload.github.com/jdm/webrender/tar.gz/920168aff79a7cf52980b0c90965a591f2f4204a)
WARNING:root:webrender_surfman has no source
WARNING:root:webrender_traits has no source
INFO:root:started sha256(https://codeload.github.com/servo/webxr/tar.gz/af2e84a28d52521212816584e0553aaf364a9162)
INFO:root:started sha256(https://codeload.github.com/servo/webxr/tar.gz/af2e84a28d52521212816584e0553aaf364a9162)
INFO:root:started sha256(https://codeload.github.com/gfx-rs/wgpu/tar.gz/e72724a6e393503c73f37e86aa9317a5c62e32b8)
INFO:root:started sha256(https://codeload.github.com/gfx-rs/wgpu/tar.gz/e72724a6e393503c73f37e86aa9317a5c62e32b8)
INFO:root:started sha256(https://codeload.github.com/rust-windowing/winit/tar.gz/4192d04a53202c199f94d1b7d883a34c9ad09272)
INFO:root:started sha256(https://codeload.github.com/jdm/webrender/tar.gz/920168aff79a7cf52980b0c90965a591f2f4204a)
INFO:root:done sha256(https://codeload.github.com/servo/openxrs/tar.gz/87c0186c88f6e2bc22dbbe0bf5c02afc60fc37ef)
INFO:root:Loading packages from git https://github.com/servo/openxrs
INFO:root:done sha256(https://codeload.github.com/servo/fontsan/tar.gz/29e879c870348c4b3fd51086e42dbb6365171479)
INFO:root:Loading packages from git https://github.com/servo/fontsan
INFO:root:done sha256(https://codeload.github.com/servo/rust-mozjs/tar.gz/a8b688ad32a852172536443d77baa844f59a23fa)
INFO:root:Loading packages from git https://github.com/servo/rust-mozjs
remote: Enumerating objects: 142, done.
remote: Counting objects: 100% (138/138), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 142 (delta 77), reused 78 (delta 47), pack-reused 4
Receiving objects: 100% (142/142), 77.31 KiB | 507.00 KiB/s, done.
Resolving deltas: 100% (77/77), completed with 21 local objects.
From https://github.com/servo/rust-mozjs
 * branch            a8b688ad32a852172536443d77baa844f59a23fa -> FETCH_HEAD
Previous HEAD position was fe738cc Auto merge of #541 - sagudev:master, r=jdm
HEAD is now at a8b688a Auto merge of #548 - yvt:feat-proxy-get-prototype, r=jdm
INFO:root:done sha256(https://codeload.github.com/pcwalton/signpost/tar.gz/7ed712507f343c38646b9d1fefd049166f9c9a18)
INFO:root:Loading packages from git https://github.com/pcwalton/signpost
INFO:root:done sha256(https://codeload.github.com/servo/devices/tar.gz/cb28c4725ffbfece99dab842d17d3e8c50774778)
INFO:root:Loading packages from git https://github.com/servo/devices
INFO:root:done sha256(https://codeload.github.com/servo/openxrs/tar.gz/87c0186c88f6e2bc22dbbe0bf5c02afc60fc37ef)
INFO:root:Loading packages from git https://github.com/servo/openxrs
INFO:root:done sha256(https://codeload.github.com/servo/devices/tar.gz/cb28c4725ffbfece99dab842d17d3e8c50774778)
INFO:root:Loading packages from git https://github.com/servo/devices
INFO:root:done sha256(https://codeload.github.com/servo/mio/tar.gz/f640fd662db03026ca2a1b21ac1e161ec6f8150b)
INFO:root:Loading packages from git https://github.com/servo/mio
INFO:root:done sha256(https://codeload.github.com/gfx-rs/naga/tar.gz/b278e10ea7c144b2387585c4e81c1d86db8e2def)
INFO:root:Loading packages from git https://github.com/gfx-rs/naga
INFO:root:done sha256(https://codeload.github.com/jdm/raqote/tar.gz/ff5d2d1aa7813dbcacb0d028cf7d17c82a35d9d4)
INFO:root:Loading packages from git https://github.com/jdm/raqote
INFO:root:done sha256(https://codeload.github.com/gfx-rs/wgpu/tar.gz/e72724a6e393503c73f37e86aa9317a5c62e32b8)
INFO:root:Loading packages from git https://github.com/gfx-rs/wgpu
INFO:root:done sha256(https://codeload.github.com/gfx-rs/wgpu/tar.gz/e72724a6e393503c73f37e86aa9317a5c62e32b8)
INFO:root:Loading packages from git https://github.com/gfx-rs/wgpu
INFO:root:done sha256(https://codeload.github.com/servo/webxr/tar.gz/af2e84a28d52521212816584e0553aaf364a9162)
INFO:root:Loading packages from git https://github.com/servo/webxr
INFO:root:done sha256(https://codeload.github.com/servo/webxr/tar.gz/af2e84a28d52521212816584e0553aaf364a9162)
INFO:root:Loading packages from git https://github.com/servo/webxr
Traceback (most recent call last):
  File "/tmp/servo/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 274, in <module>
    main()
  File "/tmp/servo/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 268, in main
    generated_sources = asyncio.run(generate_sources(load_toml(args.cargo_lock),
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/tmp/servo/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 224, in generate_sources
    for pkg in await asyncio.gather(*pkg_coros):
  File "/tmp/servo/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 191, in get_package_sources
    return await get_git_sources(package, tarball=git_tarballs)
  File "/tmp/servo/flatpak-builder-tools/cargo/./flatpak-cargo-generator.py", line 156, in get_git_sources
    pkg_subpath = git_cargo_packages[name]
KeyError: 'blurmac'
```

**Comment by gasinvein** [comment]
@okias This doesn't look like output from the script from this branch. Did you checkout this PR?

**Comment by okias** [comment]
my bad, I haven't correctly applied the branch. 

Tested your PR, generation wen't well, for compilation testing, I'll do later (since Servo is pretty resource hungry)

**Comment by EmmyGH** [comment]
Sorry I got back to you so late—your PR appears to have fixed the bug! Thank you so much!

**Comment by gasinvein** [comment]
Oh well. I hope it doesn't break existing apps. Should work for at least Veloren and Pika Backup.

**Comment by okias** [comment]
Compile and run tested on Servo, works well! Thank you @gasinvein

**Comment by gasinvein** [comment]
@okias Can I see your manifest somewhere? I guess it can be useful for testing this sources generator.

**Pull request merged**
