### PR TITLE
Npm git module generation

### PR DESCRIPTION
**Pull request by adityashah1212**
npm has support to pull modules directly from git repo. This pr adds support to create modules for such modules. It also generates a patch script to patch the package-lock.json and package.json, so as to use these local copies.

### CODE REVIEW

**Comment by nedrichards** [comment]
@adityashah1212 needs a rebase to resolve conflicts, but other than that lgtm

**Comment by adityashah1212** [comment]
rebased now merging

**Comment by alexlarsson** [comment]
Hmm, this is not working for me.
betaflight-configurator has a dependency on `github:adam-lynch/node-temp#279c1350cb7e4f02515d91da9e35d39a40774016` but when it is converted to a local git repo i get:
```
npm ERR! path /app/npm-git-modules/node-temp/node_modules/rimraf
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/app/npm-git-modules/node-temp/node_modules/rimraf' -> '/app/npm-git-modules/node-temp/node_modules/.rimraf.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
Due to the dependency on the rimraf module. It looks like it expects such git repos to be fully resolved.

**Comment by alexlarsson** [comment]
It seems to wrok better if i use git+file: uris.

**Pull request merged**
