### PR TITLE
cargo: Enable shallow git clone

### PR DESCRIPTION
**Pull request by ThejasKiranPS**
Enables [shallow clone](https://www.git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) to reduce download size.

### CODE REVIEW

**Comment by ThejasKiranPS** [comment]
Oh sorry. Just noticed there exists some 'git checkout' commands too. Is it only working with commit of HEAD?
If not, feel free to close this pr :)

**Comment by gasinvein** [comment]
> Is it only working with commit of HEAD?

No, a `Cargo.lock` can specify arbitrary commit we'll need to fetch. So, I guess making the initial clone shallow will save us some download time, but not much.

**Comment by ThejasKiranPS** [comment]
With Cargo.lock file of [gstreamer-rs](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs) the time it took was around 3 seconds compared to 50+ sec in normal clone.

**Comment by gasinvein** [comment]
This seems unusual, but, well, I guess this change won't hurt anyway.

**Comment by ThejasKiranPS** [comment]
@gasinvein Hey, could you please add `hacktoberfest-accepted` label in this PR? I'm participating in hactoberfest.

**Comment by gasinvein** [comment]
Ugh, ok.

**Pull request merged**
