### PR TITLE
Fixes to flatpak-cargo-generator

### PR DESCRIPTION
**Pull request by zecakeh**
Various errors I encountered while trying the script and then to build a Flatpak app.

See each commit message for details.

See the last commit of https://github.com/flathub/org.gnome.Fractal/pull/41 for the differences in the generated sources.

### CODE REVIEW

**Comment by hfiguiere** [comment]
I wonder how this intersects with #323 and #325.

**Comment by hfiguiere** [comment]
and also #399

**Comment by hfiguiere** [comment]
And issue #367, seems that this would fix it.

**Comment by zecakeh** [comment]
After checking all of those:

- There is no direct link/conflict with #323, although I don't recommend to merge it.
- There is no direct link/conflict with #325.
- The last commit of this PR is not necessary if #399 is merged (which I recommend over #323).
- It could possibly fix #367, if we knew what the actual error looks like, and if we could reproduce it.

**Comment by zecakeh** [comment]
I rebased on master and dropped the last commit, to fix conflicts.

**Comment by hfiguiere** [comment]
thanks!

**Pull request merged**
